"""
Django settings for mesotheliomalegalhelpcenter project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent


DEBUG=config("DEBUG")
SECRET_KEY = config("SECRET_KEY")
ALLOWED_HOSTS = [config("PRIMARY_DOMAIN"),config("SECONDARY_DOMAIN")]



INSTALLED_APPS = [
    'jazzmin',
    'compressor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'tinymce',

    'content_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mesotheliomalegalhelpcenter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mesotheliomalegalhelpcenter.wsgi.application'

if config("MODE") == "prod":
    DATABASES = {
      'default': {
        'HOST': config("DATABASE_HOST"),
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'USER': config("DATABASE_USER"),
        'PASSWORD': config("DATABASE_PASS"),
        'NAME': config("DATABASE_NAME"),
        'PORT': config("DATABASE_PORT")
      },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if config("MODE") == "prod":
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    LINODE_BUCKET=config("BUCKET_NAME")
    LINODE_BUCKET_REGION=config("BUCKET_REGION")
    LINODE_BUCKET_ACCESS_KEY=config("LINODE_BUCKET_ACCESS_KEY")
    LINODE_BUCKET_SECRET_KEY=config("LINODE_BUCKET_SECRET_KEY")


    AWS_S3_ENDPOINT_URL=f'https://{LINODE_BUCKET_REGION}.linodeobjects.com'
    AWS_ACCESS_KEY_ID=LINODE_BUCKET_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY=LINODE_BUCKET_SECRET_KEY
    AWS_S3_REGION_NAME=LINODE_BUCKET_REGION
    AWS_S3_USE_SSL=True
    AWS_STORAGE_BUCKET_NAME=LINODE_BUCKET

else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    MEDIA_URL = config('MEDIA')

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

COMPRESS_ENABLED = True
COMPRESS_CSS_HASHING_METHOD = 'content'
COMPRESS_FILTERS = {
    'css':[
        'compressor.filters.css_default.CssAbsoluteFilter',
        'compressor.filters.cssmin.rCSSMinFilter',
    ],
    'js':[
        'compressor.filters.jsmin.JSMinFilter',
    ]
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Admin Panel settings
JAZZMIN_SETTINGS = {
    "site_title": "Admin Panel",
    "search_model": ["content_manager.Articles",],
    "show_ui_builder": True,
    "related_modal_active": True,
    "custom_css": "jazzmin/css/custom_main.css",
    "changeform_format": "single",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "simplex",
}

# TINYMCE SETTINGS
TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 800,
    "width": 800,
    "menubar": True,
    "plugins": "advlist,autolink,lists,link,image,charmap,print,preview,"
               "anchor,searchreplace,visualblocks,code,fullscreen,insertdatetime,"
               "media,table,paste,code,help,wordcount",
    "toolbar": "undo redo | formatselect | bold italic backcolor | "
               "alignleft aligncenter | alignright alignjustify | "
               "bullist numlist outdent indent | removeformat ",

    'images_upload_url': '/upload_image/',
    # 'automatic_uploads': True,
    # 'images_upload_base_path': 'media/tinymce_image',
    # 'image_uploadtab': True,
    'image_advtab': True,
}