"""
Django settings for mesotheliomalegalhelpcenter project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent


# ENV = os.environ.get('ENV')
# if int(os.environ.get('SECRET_KEY_VALUE', default=1)):
#     SECRET_KEY = config('SECRET_KEY', cast=str)
# else:
#     SECRET_KEY = os.environ['SECRET_KEY']
#
# DEBUG = int(os.environ.get("DEBUG", default=1))
# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(" ") if os.environ.get('ALLOWED_HOSTS') else ['localhost', '127.0.0.1']

# ENV = os.environ.get('ENV')
# if int(os.environ.get('SECRET_KEY_VALUE', default=1)):
#     SECRET_KEY = config('SECRET_KEY', cast=str)
# else:
#     SECRET_KEY = os.environ['SECRET_KEY']
DEBUG=True
SECRET_KEY = 'django-insecure-g)z*i=2ox+6rwfxo-b236a&t7@)m7!uw3jz(-l_o&z89rb)^-8'
# DEBUG = int(os.environ.get("DEBUG", default=1))
# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(" ") if os.environ.get('ALLOWED_HOSTS') else ['localhost', '127.0.0.1']
# ALLOWED_HOSTS = ['139.144.227.212']
ALLOWED_HOSTS = ['*']



INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'tinymce',

    'content_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mesotheliomalegalhelpcenter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mesotheliomalegalhelpcenter.wsgi.application'

if int(os.environ.get('DATABASEUSE', default=1)):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
      'default': {
        'HOST': os.environ['PMA_HOST'],
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'NAME': os.environ['POSTGRES_DB'],
      },
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# if int(os.environ['GAE_APPLICATION']):
#     DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
#     GS_BUCKET_NAME = 'media_mesothelioma_how'
#     GS_DEFAULT_ACL = 'publicRead'
#     MEDIA_URL = 'https://storage.googleapis.com/media_mesothelioma_how/'
# else:
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Admin Panel settings
JAZZMIN_SETTINGS = {
    "site_title": "Admin Panel",
    "search_model": ["content_manager.Articles",],
    "show_ui_builder": True,
    "related_modal_active": True,
    "custom_css": "jazzmin/css/custom_main.css",
    "changeform_format": "single",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "simplex",
}

# TINYMCE SETTINGS
TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 800,
    "width": 800,
    "menubar": True,
    "plugins": "advlist,autolink,lists,link,image,charmap,print,preview,"
               "anchor,searchreplace,visualblocks,code,fullscreen,insertdatetime,"
               "media,table,paste,code,help,wordcount",
    "toolbar": "undo redo | formatselect | bold italic backcolor | "
               "alignleft aligncenter | alignright alignjustify | "
               "bullist numlist outdent indent | removeformat ",

    'images_upload_url': '/upload_image/',
    # 'automatic_uploads': True,
    # 'images_upload_base_path': 'media/tinymce_image',
    # 'image_uploadtab': True,
    'image_advtab': True,
}