# Generated by Django 3.2 on 2023-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='snippet',
            field=models.TextField(blank=True),
        ),
    ]
