# Generated by Django 3.2 on 2023-02-28 16:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='article',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
