# Generated by Django 3.2 on 2023-03-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0002_alter_articlesmodel_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='dropdown_select',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
