# Generated by Django 3.2 on 2023-02-24 11:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0002_categorymodel_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
